#!/usr/bin/env bash
#
# Capture every screen of the iOS client from a booted simulator.
#
# Why this exists
# ---------------
# The web client has 21 committed screenshots, generated by
# `e2e/screenshots.spec.ts`. This client had one: the launch screen. Everything
# else the app does - the dashboard, the battle, the album, the progress page,
# both languages - existed only as prose in mobile/README.md, so a screen that
# quietly stopped rendering on iOS would look exactly like a screen that was
# never photographed.
#
# This script drives the app through its screens on a simulator the caller has
# already booted and built for, screenshots each one, and reads the pixels back
# with Vision OCR before accepting the capture. It is the macOS half of the
# record; `audit_ios_screenshots.py` is the half that re-checks the committed
# files on every push, with no simulator.
#
#
# How the UI is driven, and why it is done this way
# ------------------------------------------------
# `xcrun simctl` can install, launch, screenshot and open a URL. It cannot tap.
# Three ways to get past that were considered:
#
#   1. Synthetic taps against the Simulator window (osascript / cliclick).
#      Rejected: it needs Accessibility (TCC) permission that a GitHub runner
#      does not grant, and it turns every capture into a bet on window
#      position, scale and chrome.
#
#   2. An XCUITest target. Rejected: `expo prebuild --clean` regenerates the
#      Xcode project on every CI run, so a committed UI-test target is deleted
#      before it can run. Keeping one would mean an Expo config plugin that
#      injects a native target, plus `build-for-testing`/`test-without-building`
#      - a large native dependency to take a picture.
#
#   3. A deep link that selects the screen. Chosen. `app.json` already declares
#      `"scheme": "mathmon"`, so `expo prebuild` writes the URL type into
#      Info.plist for free, `Linking` is React Native core (no new native
#      module, no new pod), and `xcrun simctl openurl` delivers a URL to an app
#      that is *already running* - so the whole set is captured from one cold
#      start instead of one launch per screen.
#
# The tradeoff of (3) is that it puts a hook in shipping code: App.tsx maps
# `mathmon://screen/<name>` onto the same `setScreen` the buttons call. That is
# the same navigation a tap performs and nothing more - deliberately *not* a
# way to inject state. Which is why the save is seeded through the filesystem
# below rather than through the URL: a deep link that could overwrite a child's
# album would be a real hole, and it would live in the shipping app forever to
# save a test twenty lines.
#
#
# Seeding the save
# ----------------
# Every screen after sign-up needs a profile, and a fresh simulator has none.
# The fixture is written straight into the app's AsyncStorage container while
# the app is not running: `Library/Application Support/<bundle id>/
# RCTAsyncLocalStorage_V1/`, a `manifest.json` mapping the key to null and the
# value in a file named after the MD5 of the key. That is RNCAsyncStorage's
# own out-of-line format (see its `_writeEntry` / `_filePathForKey`).
#
# This does couple the harness to a private on-disk layout, which is a real
# cost. It buys the absence of a "load this profile" entry point in the app.
# And it cannot fail *quietly*: if the layout ever changes, the seed lands
# nowhere, the app opens on sign-up, and the OCR assertion for the very next
# screen fails by name.
#
#
# Usage
# -----
#   mobile/scripts/capture_screens.sh <simulator-udid> <path/to/Built.app> [out-dir]
#
# Defaults to writing mobile/docs/screens/. Every capture is OCR-asserted, and
# the whole set is handed to audit_ios_screenshots.py --require-complete at the
# end, so this script cannot succeed while producing a blank, duplicated or
# malformed record.
#
# Exit status: 0 every screen captured and read back; 1 a capture failed; 2 the
# harness could not run (bad arguments, no such app, no simulator).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MOBILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# The screens to capture.
#
# One record per capture:
#
#   name | phase | deep-link path | expected on-screen text...
#
# `phase` is the save the app is running on: `fresh` (no profile at all, which
# is the only way to photograph sign-up), `played-en`, `played-zh`. Screens are
# grouped by phase because switching phases costs a relaunch.
#
# An empty deep-link path means "whatever the app opens on", used by the
# sign-up shot, where there is no profile and the router never reaches the
# switch.
#
# The expected text is asserted against the captured pixels by Vision OCR. It
# is what makes a capture evidence rather than a picture: a redbox, a blank
# screen and the wrong screen all fail here.
#
# `audit_ios_screenshots.py` parses this array for the expected file names, so
# this list is the single source of truth for what the record contains - the
# audit never writes a second copy of it down.
# ---------------------------------------------------------------------------
SCREENS=(
  "01-sign-up|fresh||Mathmon Battle League|Catch monsters|trainer name"
  # "Hello, Leo" and "Blazur" are the two strings that prove the seed landed
  # *and* the shared engine ran: the fixture stores starterId cindik and 900 xp,
  # and only `partnerFor` turns that into the stage-2 Blazur.
  "02-dashboard|played-en|screen/home|Hello, Leo|Blazur|Maths level"
  "03-choose-opponent|played-en|screen/pick|Choose your opponent|Type chart"
  # Asserting the opponent's name proves the deep link's parameter was honoured
  # rather than a default fight being started.
  "04-battle|played-en|screen/battle?opponent=vinari|wild creature appeared|Pick your move|Vinari"
  "05-album|played-en|screen/album|Creature album|Ember"
  "06-progress|played-en|screen/progress|Your progress|Maths skills|Badges"
  "07-settings|played-en|screen/settings|Settings|Language|Sound"
  "08-sign-in|played-en|screen/signin|Sign in to save|4-digit PIN"
  # The Chinese pair is seeded from a profile identical to the English one
  # except for settings.language, which is what makes P5 (no two captures are
  # the same picture) a real check on the translation: if the language never
  # applied, these files would be byte-identical to 02 and 05. That is exactly
  # the bug that shipped on the web client, where 12-chinese.png was a copy of
  # an English dashboard for weeks.
  #
  # Only the screen titles are asserted, in large type. mobile/README.md
  # records why the smaller Chinese strings are left out: Vision reads a 13pt
  # 小火星 as "JKE" often enough that asserting it would be a flaky test about
  # OCR rather than a real one about the app.
  "09-chinese-dashboard|played-zh|screen/home|数学宝贝对战联盟"
  "10-chinese-album|played-zh|screen/album|伙伴图鉴"
)

# Cold start: Metro is not involved (Release embeds the bundle), but the JS
# still has to boot, read the save and render.
LAUNCH_SETTLE_SECONDS=12
# A deep link is a setState on an app that is already warm.
NAVIGATE_SETTLE_SECONDS=3
# Screens that animate in (the hit shake, the speed meter) can be caught
# mid-frame, and a cold simulator occasionally needs longer than the settle
# above. Re-screenshot rather than sleeping longer for everyone. Kept low
# because each attempt runs the Vision script, and `swift file.swift` compiles
# before it runs - the retries are the expensive part of this script, not the
# screenshots.
CAPTURE_ATTEMPTS=3
RETRY_SECONDS=3

die() {
  echo "::error::capture_screens: $*" >&2
  exit 2
}

note() { echo "==> $*"; }

# ---------------------------------------------------------------------------
# Arguments and preconditions
# ---------------------------------------------------------------------------

[ $# -ge 2 ] || die "usage: capture_screens.sh <simulator-udid> <path/to/Built.app> [out-dir]"

UDID="$1"
APP="$2"
OUT_DIR="${3:-$MOBILE_DIR/docs/screens}"

command -v xcrun >/dev/null 2>&1 || die "xcrun not found - this script needs macOS with Xcode"
[ -d "$APP" ] || die "no .app at $APP"
[ -f "$APP/Info.plist" ] || die "$APP has no Info.plist"

# The same guard the simulator job applies before launching, repeated here so
# this script is honest when run by hand. A simulator Debug build ships no
# JavaScript: it installs, launches, stays alive and renders the "No script URL
# provided" redbox. Ten screenshots of a redbox is precisely the green run this
# whole exercise exists to make impossible.
[ -f "$APP/main.jsbundle" ] ||
  die "$APP contains no main.jsbundle - this is a Debug build and every capture would be a redbox"

BUNDLE_ID="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$APP/Info.plist")"
[ -n "$BUNDLE_ID" ] || die "could not read CFBundleIdentifier from $APP/Info.plist"

# Read the two strings this script would otherwise hard-code out of the app
# itself. A second copy of either is a second thing to drift.
STORAGE_KEY="$(sed -nE "s/^export const STORAGE_KEY = '(.+)';[[:space:]]*$/\1/p" \
  "$MOBILE_DIR/src/storage.ts" | head -1)"
[ -n "$STORAGE_KEY" ] || die "could not parse STORAGE_KEY out of mobile/src/storage.ts"

SCHEME="$(sed -nE 's/^[[:space:]]*"scheme":[[:space:]]*"([^"]+)".*$/\1/p' \
  "$MOBILE_DIR/app.json" | head -1)"
[ -n "$SCHEME" ] || die "could not parse the URL scheme out of mobile/app.json"

# The same save the web screenshots are taken from (PLAYED_PROFILE in
# e2e/screenshots.spec.ts), so the two records show one game part-way through
# rather than two different ones. It round-trips `normaliseProfile` unchanged;
# if it ever stops doing so the repaired fields simply appear on screen, and
# the OCR assertions below are what notice.
FIXTURE="$SCRIPT_DIR/fixtures/played-profile.json"
[ -f "$FIXTURE" ] || die "no profile fixture at $FIXTURE"

mkdir -p "$OUT_DIR"

note "app          $APP"
note "bundle id    $BUNDLE_ID"
note "simulator    $UDID"
note "scheme       $SCHEME://"
note "storage key  $STORAGE_KEY"
note "output       $OUT_DIR"

# ---------------------------------------------------------------------------
# Simulator plumbing
# ---------------------------------------------------------------------------

# Apple's own convention for a marketing screenshot, and a determinism win: the
# clock, the battery and the signal bars are the only pixels on these screens
# that would otherwise change between two runs of a build that changed nothing,
# and every one of them would show up as a diff in the committed record.
freeze_status_bar() {
  if ! xcrun simctl status_bar "$UDID" override \
    --time "9:41" \
    --dataNetwork wifi --wifiMode active --wifiBars 3 \
    --cellularMode active --cellularBars 4 \
    --batteryState charged --batteryLevel 100 2>/dev/null; then
    echo "warning: could not override the status bar; captures will show the runner's clock" >&2
  fi
}

reinstall_clean() {
  xcrun simctl terminate "$UDID" "$BUNDLE_ID" >/dev/null 2>&1 || true
  xcrun simctl uninstall "$UDID" "$BUNDLE_ID" >/dev/null 2>&1 || true
  xcrun simctl install "$UDID" "$APP"
}

# Writes a profile into the app's AsyncStorage container, in RNCAsyncStorage's
# out-of-line format: the manifest maps the key to null and the value lives in
# a file named after the MD5 of the key. Writing it out-of-line unconditionally
# is correct for a value of any size - the read path checks the manifest for
# null and goes to the file - and avoids depending on the 1024-character inline
# threshold as well as on the layout.
#
# The app must not be running: it holds the manifest in memory and would write
# its own back over this one.
seed_profile() {
  local json="$1"
  local container dir hashed

  container="$(xcrun simctl get_app_container "$UDID" "$BUNDLE_ID" data)" ||
    die "no data container for $BUNDLE_ID - is it installed?"
  dir="$container/Library/Application Support/$BUNDLE_ID/RCTAsyncLocalStorage_V1"
  hashed="$(printf '%s' "$STORAGE_KEY" | md5 -q)"

  mkdir -p "$dir"
  cp "$json" "$dir/$hashed"
  printf '{"%s":null}' "$STORAGE_KEY" >"$dir/manifest.json"
}

launch_app() {
  xcrun simctl terminate "$UDID" "$BUNDLE_ID" >/dev/null 2>&1 || true
  xcrun simctl launch "$UDID" "$BUNDLE_ID" >/dev/null
  sleep "$LAUNCH_SETTLE_SECONDS"
}

# The Chinese fixture is the English one with a single field changed, generated
# rather than committed twice. Two fixture files would be two things to keep in
# step, and the moment they drifted the Chinese captures would stop being the
# same save in another language - which is the only reason they prove anything.
chinese_fixture() {
  local src="$1" dest="$2"
  sed 's/"language": "en"/"language": "zh"/' "$src" >"$dest"
  if cmp -s "$src" "$dest"; then
    die "the Chinese fixture is identical to the English one - the language field in $(basename "$src") no longer matches the substitution"
  fi
}

# ---------------------------------------------------------------------------
# Capture
# ---------------------------------------------------------------------------

# Screenshot, then read the pixels back. A screenshot always succeeds; only the
# OCR distinguishes the screen from a redbox, a blank frame, or the screen
# before the one asked for.
capture() {
  local name="$1"
  shift
  local expected=("$@")
  local path="$OUT_DIR/$name.png"
  local attempt=1
  local ocr_log

  ocr_log="$(mktemp)"

  while [ "$attempt" -le "$CAPTURE_ATTEMPTS" ]; do
    xcrun simctl io "$UDID" screenshot --type=png "$path" >/dev/null

    if swift "$SCRIPT_DIR/assert-screenshot-text.swift" "$path" "${expected[@]}" >"$ocr_log" 2>&1; then
      note "captured $name.png (attempt $attempt)"
      rm -f "$ocr_log"
      return 0
    fi

    attempt=$((attempt + 1))
    # An `&&` here would be a bug rather than shorthand: on the last attempt the
    # test fails, the AND-list exits non-zero, and `set -e` kills the script
    # before the OCR log below is ever printed.
    if [ "$attempt" -le "$CAPTURE_ATTEMPTS" ]; then sleep "$RETRY_SECONDS"; fi
  done

  echo "--- OCR output for $name (last of $CAPTURE_ATTEMPTS attempts) ---" >&2
  cat "$ocr_log" >&2
  rm -f "$ocr_log"
  echo "::error::$name: the screen never showed ${expected[*]}" >&2
  # The file is left on disk on purpose: whatever it photographed is the most
  # useful thing in the log, and the CI step uploads this directory.
  exit 1
}

navigate() {
  local path="$1"
  xcrun simctl openurl "$UDID" "$SCHEME://$path"
  sleep "$NAVIGATE_SETTLE_SECONDS"
}

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT
chinese_fixture "$FIXTURE" "$WORK_DIR/played-zh.json"

freeze_status_bar

current_phase=""
for record in "${SCREENS[@]}"; do
  # Non-whitespace IFS, so `a||b` keeps the empty field rather than collapsing
  # it - which is what lets the sign-up record carry no deep link.
  IFS='|' read -r -a fields <<<"$record"
  name="${fields[0]}"
  phase="${fields[1]}"
  link="${fields[2]}"
  expected=("${fields[@]:3}")

  if [ "$phase" != "$current_phase" ]; then
    note "phase: $phase"
    case "$phase" in
      fresh)
        # A reinstall is the only way to be sure there is no save: the sign-up
        # screen is unreachable once one exists.
        reinstall_clean
        ;;
      played-en)
        reinstall_clean
        seed_profile "$FIXTURE"
        ;;
      played-zh)
        reinstall_clean
        seed_profile "$WORK_DIR/played-zh.json"
        ;;
      *)
        die "unknown phase '$phase' for $name"
        ;;
    esac
    launch_app
    current_phase="$phase"
  fi

  # Same trap as above, and this one is worse: the sign-up record has no deep
  # link, so `[ -n "$link" ] && navigate` would end the run under `set -e`
  # before a single screen was captured.
  if [ -n "$link" ]; then navigate "$link"; fi
  capture "$name" "${expected[@]}"
done

xcrun simctl terminate "$UDID" "$BUNDLE_ID" >/dev/null 2>&1 || true
xcrun simctl status_bar "$UDID" clear >/dev/null 2>&1 || true

note "all ${#SCREENS[@]} screens captured into $OUT_DIR"

# The same audit that guards the committed record, run against what was just
# produced - with --require-complete, because on this side of the fence every
# screen in the list has just been captured, so a missing one is a failure
# rather than a note.
python3 "$SCRIPT_DIR/audit_ios_screenshots.py" --require-complete "$OUT_DIR"
