#!/usr/bin/env python3
"""Audit the "no third-party assets" claim that README.md and CLAUDE.md make.

Both files promise, in the user's own words, "non-copyrighted material":

    "The creatures are original. There are no Nintendo assets, names, or
     sprites anywhere in this repository, and there should never be."
    "No image, font, or audio assets ship with this app."

Until this script existed, nothing enforced that. A single dropped .png, a
`<link>` to fonts.googleapis.com, or a creature named after someone else's
would have falsified the claim silently. This turns it into an invariant that
CI checks on every push.

Four checks:

  A. Binary media committed anywhere outside the documentation directories.
  B. References to external asset hosts / remote font and image URLs, split
     into "in code" (a real dependency, fails) and "in a comment" (prose about
     a URL, reported but does not fail).
  C. Nintendo / Pokemon trademarked creature names in shipped source.
  D. A size census, so "the art is procedural geometry, not assets" is a
     number a reader can check rather than a sentence they have to trust.

Standard library only, no network, no clock, no randomness. Output is sorted
and byte-identical across runs, so a diff in CI output means a diff in the
repository.

Usage:
    python3 scripts/audit_assets.py            # audit; exit 1 on violation
    python3 scripts/audit_assets.py --quiet    # findings and totals only

Exit codes:  0 = clean   1 = violations found   2 = could not run the audit
"""

from __future__ import annotations

import bisect
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SELF_PATH = "scripts/audit_assets.py"


# --------------------------------------------------------------------------
# What counts as a media asset
# --------------------------------------------------------------------------

# Opaque blobs. You cannot review these in a diff, and they are exactly the
# shape a copied sprite or a licensed font arrives in. Zero tolerance outside
# the documentation directories.
BINARY_MEDIA_EXTS = frozenset(
    {
        ".png",
        ".jpg",
        ".jpeg",
        ".gif",
        ".webp",
        ".mp3",
        ".wav",
        ".ogg",
        ".ttf",
        ".otf",
        ".woff",
        ".woff2",
        ".mp4",
    }
)

# SVG is text, so it is reviewable in a diff in a way a .png is not - but it is
# still a shipped image asset, so it is held to the same rule and needs an
# explicit, justified allowlist entry to exist at all.
VECTOR_MEDIA_EXTS = frozenset({".svg"})

MEDIA_EXTS = BINARY_MEDIA_EXTS | VECTOR_MEDIA_EXTS

# Documentation, not shipped code. The screenshots are generated by the E2E
# suite from the app's own UI, and the iOS launch shot is proof the simulator
# job runs. Neither reaches a player's browser.
DOC_MEDIA_DIRS = ("docs/screenshots/", "mobile/docs/")

# Directories whose entire contents are served to a client verbatim. These are
# checked separately and loudly, because a stray file here is not just
# committed, it is *shipped*.
SHIPPED_ASSET_DIRS = ("public/", "mobile/assets/")


@dataclass(frozen=True)
class MediaAllowance:
    """One media file permitted to exist, with the reason recorded in-repo."""

    path: str
    reason: str
    max_bytes: int


# Every entry here is a deliberate, reviewed exception. The audit does not take
# an allowance on trust: it re-verifies the file is still small, still text,
# still free of remote references and still free of an embedded raster. An
# allowance permits *this* file as it is, not "any file at this path".
MEDIA_ALLOWANCES = (
    MediaAllowance(
        path="public/icon.svg",
        reason=(
            "Hand-authored app icon (favicon + PWA manifest icon), original "
            "geometry written as inline vector primitives in this repository. "
            "Referenced by src/app/layout.tsx and public/manifest.webmanifest. "
            "Text, reviewable in a diff, no raster and no remote fetch."
        ),
        max_bytes=8192,
    ),
)

# The SVG XML namespace is a URL that identifies a spec; it is never fetched.
# Both client renderers emit it, so it must not read as a remote dependency.
SVG_NAMESPACE = "http://www.w3.org/2000/svg"


# --------------------------------------------------------------------------
# Check B: external asset hosts and remote media URLs
# --------------------------------------------------------------------------

REMOTE_HOST_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"fonts\.googleapis\.com", "Google Fonts stylesheet host"),
    (r"fonts\.gstatic\.com", "Google Fonts binary host"),
    (r"use\.typekit\.net", "Adobe Typekit font host"),
    (r"use\.fontawesome\.com", "Font Awesome CDN"),
    (r"\bcdn\.[a-z0-9-]+\.[a-z]{2,}", "generic CDN hostname"),
    (r"\bunpkg\.com", "unpkg CDN"),
    (r"\bjsdelivr\.net", "jsDelivr CDN"),
    (r"\bimgur\.com", "imgur image host"),
    (r"raw\.githubusercontent\.com", "GitHub raw file host"),
    (r"\bcloudfront\.net", "CloudFront CDN"),
    (r"\bakamaihd\.net", "Akamai CDN"),
    (r"googleusercontent\.com", "Google user content host"),
    (r"\.s3\.amazonaws\.com|\bs3\.amazonaws\.com", "S3 bucket host"),
    (r"\bplacehold(?:er)?\.(?:co|it|com)", "placeholder image service"),
    (r"\bvia\.placeholder\.com", "placeholder image service"),
)

_MEDIA_URL_EXTS = "png|jpe?g|gif|webp|svg|mp3|wav|ogg|ttf|otf|woff2?|mp4"

REMOTE_STRUCTURE_PATTERNS: tuple[tuple[str, str], ...] = (
    (
        rf"https?://[^\s'\"()<>]+\.(?:{_MEDIA_URL_EXTS})\b",
        "remote media URL",
    ),
    (r"<link[^>]+href\s*=\s*['\"]https?://", "remote <link> stylesheet/icon"),
)

# CSS-only patterns. These are kept out of the general set because JavaScript's
# `new URL('https://accounts.google.com/...')` is textually `URL(https://` and
# matched the CSS url() rule - flagging an OAuth redirect, which fetches no
# asset at all, as a remote asset dependency. The first run of this audit
# caught exactly that, so the rule now applies only where CSS url() syntax
# actually means something.
REMOTE_CSS_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"@import\s+url\(\s*['\"]?https?://", "remote CSS @import"),
    (r"\burl\(\s*['\"]?https?://", "remote CSS url() reference"),
)


# --------------------------------------------------------------------------
# Check C: trademarked names
# --------------------------------------------------------------------------

# Franchise and company terms. "poke ball" style spellings included because the
# item name is as trademarked as the creatures are.
TRADEMARK_TERMS: tuple[str, ...] = (
    "pokemon",
    "pokémon",
    "poké ball",
    "pokeball",
    "poke ball",
    "pokedex",
    "pokédex",
    "nintendo",
    "game freak",
    "creatures inc",
    "gotta catch em all",
    "gotta catch 'em all",
)

# First-generation creature names that are unambiguous - none of these is an
# ordinary English word, so a match is a finding, not a coincidence.
TRADEMARK_NAMES: tuple[str, ...] = (
    "bulbasaur",
    "ivysaur",
    "venusaur",
    "charmander",
    "charmeleon",
    "charizard",
    "squirtle",
    "wartortle",
    "blastoise",
    "caterpie",
    "metapod",
    "butterfree",
    "weedle",
    "kakuna",
    "beedrill",
    "pidgey",
    "pidgeotto",
    "pidgeot",
    "rattata",
    "raticate",
    "spearow",
    "fearow",
    "ekans",
    "arbok",
    "pikachu",
    "raichu",
    "sandshrew",
    "sandslash",
    "nidoran",
    "nidorina",
    "nidoqueen",
    "nidorino",
    "nidoking",
    "clefairy",
    "clefable",
    "vulpix",
    "ninetales",
    "jigglypuff",
    "wigglytuff",
    "zubat",
    "golbat",
    "oddish",
    "gloom",
    "vileplume",
    "parasect",
    "venonat",
    "venomoth",
    "diglett",
    "dugtrio",
    "meowth",
    "psyduck",
    "golduck",
    "mankey",
    "primeape",
    "growlithe",
    "arcanine",
    "poliwag",
    "poliwhirl",
    "poliwrath",
    "kadabra",
    "alakazam",
    "machop",
    "machoke",
    "machamp",
    "bellsprout",
    "weepinbell",
    "victreebel",
    "tentacool",
    "tentacruel",
    "geodude",
    "graveler",
    "ponyta",
    "rapidash",
    "slowbro",
    "magnemite",
    "magneton",
    "farfetch",
    "doduo",
    "dodrio",
    "dewgong",
    "grimer",
    "shellder",
    "cloyster",
    "gastly",
    "gengar",
    "onix",
    "drowzee",
    "krabby",
    "kingler",
    "voltorb",
    "exeggcute",
    "exeggutor",
    "cubone",
    "marowak",
    "hitmonlee",
    "hitmonchan",
    "lickitung",
    "koffing",
    "weezing",
    "rhyhorn",
    "rhydon",
    "chansey",
    "tangela",
    "kangaskhan",
    "horsea",
    "seadra",
    "goldeen",
    "seaking",
    "staryu",
    "starmie",
    "scyther",
    "jynx",
    "electabuzz",
    "magmar",
    "pinsir",
    "tauros",
    "magikarp",
    "gyarados",
    "lapras",
    "eevee",
    "vaporeon",
    "jolteon",
    "flareon",
    "porygon",
    "omanyte",
    "omastar",
    "kabuto",
    "kabutops",
    "aerodactyl",
    "snorlax",
    "articuno",
    "zapdos",
    "moltres",
    "dratini",
    "dragonair",
    "dragonite",
    "mewtwo",
)

# Also trademarked, but each is a perfectly ordinary English word as well. They
# are still checked - a creature called Golem would be as much of a problem as
# one called Pikachu - but they are reported in their own section so a reviewer
# knows the match may be innocent prose before anyone renames anything.
AMBIGUOUS_TRADEMARK_NAMES: tuple[str, ...] = (
    "ditto",
    "golem",
    "mew",
    "seel",
    "electrode",
    "hypno",
    "slowpoke",
    "haunter",
    "muk",
    "paras",
    "persian",
    "abra",
    "psyduck",
)


@dataclass(frozen=True)
class NameAllowance:
    """A trademarked token permitted in one specific file, with a reason."""

    path: str
    token: str
    reason: str


NAME_ALLOWANCES = (
    NameAllowance(
        path="src/lib/game/creatures.test.ts",
        token="mewtwo",
        reason=(
            "Negative test: asserts getCreature('mewtwo') throws and "
            "findCreature('mewtwo') is undefined. The name appears in order to "
            "prove it is NOT in the roster, which is evidence for the claim "
            "rather than against it."
        ),
    ),
)


# Documentation legitimately discusses what this project deliberately does not
# contain - "A note on Pokemon" in README.md is the whole point. Scanning it
# would make the audit fail for saying the true thing out loud.
DOC_PATH_PREFIXES = ("docs/", "mobile/docs/")
DOC_FILE_SUFFIXES = (".md",)

# Dependency metadata, not authored source. `integrity` values are base64 and
# will eventually contain any short letter sequence by chance; those lines are
# skipped, but package names and resolved URLs stay in scope so a dependency
# named after the franchise would still be caught.
LOCKFILES = ("package-lock.json", "mobile/package-lock.json")
LOCKFILE_NOISE_MARKER = '"integrity":'

# The repository itself is called `pokemon-game` and the git remote URL embeds
# that name, so the string is unavoidable in config, README badges and Vercel
# import links. Occurrences of the repo slug are masked before matching (and
# counted, so the masking is visible rather than silent).
REPO_SLUG_PATTERN = re.compile(r"pokemon[-_]game", re.IGNORECASE)


# --------------------------------------------------------------------------
# Findings
# --------------------------------------------------------------------------


@dataclass
class Finding:
    path: str
    line: int
    detail: str
    excerpt: str = ""

    def render(self) -> str:
        where = f"{self.path}:{self.line}" if self.line else self.path
        out = f"  {where}\n      {self.detail}"
        if self.excerpt:
            out += f"\n      | {self.excerpt}"
        return out


@dataclass
class Report:
    violations: dict[str, list[Finding]] = field(default_factory=dict)
    notes: dict[str, list[Finding]] = field(default_factory=dict)

    def violation(self, section: str, finding: Finding) -> None:
        self.violations.setdefault(section, []).append(finding)

    def note(self, section: str, finding: Finding) -> None:
        self.notes.setdefault(section, []).append(finding)

    @property
    def failed(self) -> bool:
        return any(self.violations.values())

    @property
    def violation_count(self) -> int:
        return sum(len(v) for v in self.violations.values())


# --------------------------------------------------------------------------
# File universe
# --------------------------------------------------------------------------


def _git(*args: str) -> list[str]:
    """Run a git command, failing loudly. Never pipe this through head/tail.

    A previous audit in this repository reported all-clear because its shell
    pipeline ended in `head`, and `head` exited 0 no matter what came before
    it. subprocess.run + an explicit returncode check is why that cannot
    happen here.
    """
    proc = subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(
            f"audit_assets: `git {' '.join(args)}` failed "
            f"({proc.returncode}): {proc.stderr.strip()}\n"
        )
        raise SystemExit(2)
    return [line for line in proc.stdout.split("\n") if line]


def collect_files() -> list[str]:
    """Tracked files plus untracked-but-not-ignored ones, sorted.

    Untracked files are included deliberately: a dropped .png should fail the
    audit the moment it lands in the working tree, not only once someone
    commits it. .gitignore is respected, which is what keeps node_modules/,
    .next/ and test-results/ out of the census.
    """
    tracked = _git("ls-files")
    untracked = _git("ls-files", "--others", "--exclude-standard")
    return sorted(set(tracked) | set(untracked))


def read_text(path: str) -> str | None:
    """Return decoded text, or None if the file is binary/unreadable."""
    try:
        with open(os.path.join(REPO_ROOT, path), "rb") as handle:
            raw = handle.read()
    except OSError:
        return None
    if b"\0" in raw:
        return None
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return None


def size_of(path: str) -> int:
    try:
        return os.path.getsize(os.path.join(REPO_ROOT, path))
    except OSError:
        return 0


def is_doc(path: str) -> bool:
    return path.startswith(DOC_PATH_PREFIXES) or path.endswith(DOC_FILE_SUFFIXES)


# --------------------------------------------------------------------------
# Comment vs code
# --------------------------------------------------------------------------

_C_FAMILY = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".swift", ".java")
_HASH_FAMILY = (".yml", ".yaml", ".py", ".sh", ".bash", ".toml", ".example")
_NO_COMMENT = (".json", ".webmanifest", ".lock")


def comment_style(path: str) -> str:
    base = os.path.basename(path)
    if base in (".gitignore", ".prettierignore", ".env.example", ".dockerignore"):
        return "hash"
    ext = os.path.splitext(path)[1].lower()
    if ext in _C_FAMILY:
        return "c"
    if ext == ".css":
        return "css"
    if ext in _HASH_FAMILY:
        return "hash"
    if ext in _NO_COMMENT:
        return "none"
    if ext in (".md", ".txt"):
        return "prose"
    return "none"


def comment_mask(text: str, style: str) -> list[bool]:
    """Per-character mask: True where the character sits inside a comment.

    This is a small state machine rather than a regex because the naive
    approach - "does the line contain // before the match" - classifies
    `const u = 'https://cdn.example.com/f.png'` as a comment, which would turn
    a real remote dependency into a silent pass. String literals are tracked,
    and `//` preceded by `:` is treated as a URL scheme, never a comment.
    """
    n = len(text)
    mask = [False] * n
    if style in ("none", "prose"):
        return mask

    if style == "c":
        line_tokens: tuple[str, ...] = ("//",)
        block: tuple[str, str] | None = ("/*", "*/")
        quotes = "'\"`"
    elif style == "css":
        line_tokens = ()
        block = ("/*", "*/")
        quotes = "'\""
    else:  # hash
        line_tokens = ("#",)
        block = None
        quotes = "'\""

    CODE, STRING, LINE_C, BLOCK_C = 0, 1, 2, 3
    state = CODE
    quote = ""
    i = 0
    while i < n:
        ch = text[i]
        if state == CODE:
            if ch in quotes:
                state, quote = STRING, ch
                i += 1
                continue
            if block is not None and text.startswith(block[0], i):
                state = BLOCK_C
                mask[i] = True
                if i + 1 < n:
                    mask[i + 1] = True
                i += 2
                continue
            opened = False
            for token in line_tokens:
                if not text.startswith(token, i):
                    continue
                if token == "//" and i > 0 and text[i - 1] == ":":
                    break  # URL scheme (https://), not a comment
                if token == "#" and i > 0 and text[i - 1] not in " \t\n":
                    break  # mid-token '#': a URL fragment or a colour literal
                state = LINE_C
                for k in range(i, min(i + len(token), n)):
                    mask[k] = True
                i += len(token)
                opened = True
                break
            if opened:
                continue
            i += 1
            continue

        if state == STRING:
            if ch == "\\":
                i += 2
                continue
            if ch == quote:
                state = CODE
            i += 1
            continue

        if state == LINE_C:
            if ch == "\n":
                state = CODE
            else:
                mask[i] = True
            i += 1
            continue

        # BLOCK_C
        mask[i] = True
        if block is not None and text.startswith(block[1], i):
            if i + 1 < n:
                mask[i + 1] = True
            i += 2
            state = CODE
            continue
        i += 1
    return mask


def line_index(text: str) -> list[int]:
    starts = [0]
    for i, ch in enumerate(text):
        if ch == "\n":
            starts.append(i + 1)
    return starts


def locate(starts: list[int], offset: int) -> int:
    return bisect.bisect_right(starts, offset)


def excerpt_at(text: str, starts: list[int], lineno: int, limit: int = 140) -> str:
    start = starts[lineno - 1]
    end = text.find("\n", start)
    if end == -1:
        end = len(text)
    line = text[start:end].strip()
    return line if len(line) <= limit else line[: limit - 1] + "…"


# --------------------------------------------------------------------------
# Check A - media files
# --------------------------------------------------------------------------


def check_media(files: list[str], report: Report) -> None:
    allowed_by_path = {a.path: a for a in MEDIA_ALLOWANCES}
    seen_allowances: set[str] = set()

    for path in files:
        ext = os.path.splitext(path)[1].lower()
        if ext not in MEDIA_EXTS:
            continue

        kind = "binary media" if ext in BINARY_MEDIA_EXTS else "vector media"
        size = size_of(path)

        if path.startswith(DOC_MEDIA_DIRS):
            report.note(
                "Documentation media (allowed - not shipped to a client)",
                Finding(path, 0, f"{kind}, {size:,} bytes"),
            )
            continue

        allowance = allowed_by_path.get(path)
        if allowance is not None:
            seen_allowances.add(path)
            problems = verify_allowance(allowance, size)
            if problems:
                for problem in problems:
                    report.violation(
                        "A. Allowlisted media file no longer meets its conditions",
                        Finding(path, 0, problem),
                    )
            else:
                report.note(
                    "Allowlisted media (reviewed exception, re-verified each run)",
                    Finding(
                        path,
                        0,
                        f"{kind}, {size:,} bytes (cap {allowance.max_bytes:,})",
                        allowance.reason,
                    ),
                )
            continue

        section = "A. Media asset committed outside the documentation directories"
        if path.startswith(SHIPPED_ASSET_DIRS):
            section = "A. Media asset in a SHIPPED directory"
        report.violation(
            section,
            Finding(
                path,
                0,
                f"{kind} ({ext}), {size:,} bytes. Allowed media locations are "
                + ", ".join(DOC_MEDIA_DIRS)
                + ". If this file is genuinely original and must ship, add a "
                "MEDIA_ALLOWANCES entry in scripts/audit_assets.py recording why.",
            ),
        )

    for allowance in MEDIA_ALLOWANCES:
        if allowance.path not in seen_allowances:
            # Not a failure: deleting an asset is the outcome this audit wants,
            # and it must never be the thing that breaks the build.
            report.note(
                "Stale allowlist entries (asset is gone - entry can be removed)",
                Finding(allowance.path, 0, "no such file in the repository"),
            )


def verify_allowance(allowance: MediaAllowance, size: int) -> list[str]:
    """Re-check an allowlisted asset. An allowance is a claim, not a bypass."""
    problems: list[str] = []
    if size > allowance.max_bytes:
        problems.append(
            f"grew to {size:,} bytes, over its {allowance.max_bytes:,} byte cap"
        )
    text = read_text(allowance.path)
    if text is None:
        problems.append("is not decodable text (an allowlisted vector must stay text)")
        return problems
    stripped = text.replace(SVG_NAMESPACE, "")
    for scheme in ("http://", "https://"):
        if scheme in stripped:
            problems.append(
                f"contains a {scheme} reference other than the SVG namespace, "
                "so it may fetch something at runtime"
            )
            break
    if "<image" in text.lower():
        problems.append("embeds a raster via <image>, defeating the point of a vector")
    if "@font-face" in text.lower() or "<font" in text.lower():
        problems.append("embeds a font")
    return problems


def check_shipped_dirs(files: list[str], report: Report) -> None:
    """Say explicitly what each shipped directory holds, present or absent."""
    for directory in SHIPPED_ASSET_DIRS:
        members = [f for f in files if f.startswith(directory)]
        if not members:
            report.note(
                "Shipped asset directories",
                Finding(
                    directory,
                    0,
                    "directory absent or empty - nothing shipped from here",
                ),
            )
            continue
        media = [f for f in members if os.path.splitext(f)[1].lower() in MEDIA_EXTS]
        total = sum(size_of(f) for f in members)
        allowed = {a.path for a in MEDIA_ALLOWANCES}
        unreviewed = sorted(set(media) - allowed)
        detail = (
            f"{len(members)} file(s), {total:,} bytes total; "
            f"{len(media)} media file(s), "
            f"{len(unreviewed)} of them unreviewed"
        )
        report.note("Shipped asset directories", Finding(directory, 0, detail))


# --------------------------------------------------------------------------
# Check B - remote asset references
# --------------------------------------------------------------------------


def check_remote_refs(files: list[str], report: Report) -> None:
    patterns = [
        (re.compile(p, re.IGNORECASE), label)
        for p, label in (*REMOTE_HOST_PATTERNS, *REMOTE_STRUCTURE_PATTERNS)
    ]
    css_patterns = [
        (re.compile(p, re.IGNORECASE), label) for p, label in REMOTE_CSS_PATTERNS
    ]

    for path in files:
        # Markdown and docs/ are prose about the project, not shipped source.
        # The Vercel deploy badge in README.md is a remote image, and that is
        # fine - it renders on GitHub, it is not part of the app.
        if is_doc(path):
            continue
        # This file necessarily contains the host list it searches for.
        if path == SELF_PATH:
            continue
        if os.path.splitext(path)[1].lower() in MEDIA_EXTS:
            continue

        text = read_text(path)
        if text is None:
            continue
        if path in LOCKFILES:
            continue

        mask = comment_mask(text, comment_style(path))
        starts = line_index(text)
        reported: set[tuple[int, str]] = set()

        # Spans of the SVG XML namespace. It is a URL, but it names a spec and
        # is never fetched; both renderers emit it on every drawing.
        ns_spans = [
            (m.start(), m.end())
            for m in re.finditer(re.escape(SVG_NAMESPACE), text)
        ]

        active = patterns
        if os.path.splitext(path)[1].lower() == ".css":
            active = patterns + css_patterns

        for regex, label in active:
            for match in regex.finditer(text):
                if any(s <= match.start() < e for s, e in ns_spans):
                    continue
                lineno = locate(starts, match.start())
                key = (lineno, label)
                if key in reported:
                    continue
                reported.add(key)
                in_comment = mask[match.start()]
                snippet = excerpt_at(text, starts, lineno)
                detail = f"{label}: {match.group(0)!r}"
                if in_comment:
                    report.note(
                        "B. Remote asset host named in a COMMENT (prose - allowed)",
                        Finding(path, lineno, detail, snippet),
                    )
                else:
                    report.violation(
                        "B. Remote asset host referenced in CODE",
                        Finding(
                            path,
                            lineno,
                            detail
                            + " - the app must fetch nothing at runtime; inline "
                            "or generate this instead",
                            snippet,
                        ),
                    )


# --------------------------------------------------------------------------
# Check C - trademarked names
# --------------------------------------------------------------------------


def _word_regex(words: tuple[str, ...]) -> re.Pattern[str]:
    alts = sorted(words, key=len, reverse=True)
    return re.compile(
        r"(?<![0-9A-Za-z])(?:" + "|".join(re.escape(w) for w in alts) + r")(?![0-9A-Za-z])",
        re.IGNORECASE,
    )


def check_trademarks(files: list[str], report: Report) -> dict[str, int]:
    hard = _word_regex(TRADEMARK_TERMS + TRADEMARK_NAMES)
    ambiguous = _word_regex(AMBIGUOUS_TRADEMARK_NAMES)
    allowed = {(a.path, a.token.lower()) for a in NAME_ALLOWANCES}
    applied_allowances: set[tuple[str, str]] = set()
    masked_totals: dict[str, int] = {}

    for path in files:
        if is_doc(path):
            continue
        if path == SELF_PATH:
            continue
        if os.path.splitext(path)[1].lower() in MEDIA_EXTS:
            continue

        text = read_text(path)
        if text is None:
            continue

        if path in LOCKFILES:
            text = "\n".join(
                "" if LOCKFILE_NOISE_MARKER in line else line
                for line in text.split("\n")
            )

        # Mask the repository's own name before matching. Same-length
        # replacement keeps every offset valid, so line numbers stay honest.
        masked_count = len(REPO_SLUG_PATTERN.findall(text))
        if masked_count:
            masked_totals[path] = masked_count
            text = REPO_SLUG_PATTERN.sub(lambda m: "#" * len(m.group(0)), text)

        starts = line_index(text)
        mask = comment_mask(text, comment_style(path))

        for regex, section in (
            (hard, "C. Trademarked name in shipped source"),
            (
                ambiguous,
                "C. Trademarked name that is also an ordinary English word "
                "(confirm before renaming)",
            ),
        ):
            for match in regex.finditer(text):
                token = match.group(0).lower()
                if (path, token) in allowed:
                    applied_allowances.add((path, token))
                    continue
                lineno = locate(starts, match.start())
                where = "comment" if mask[match.start()] else "code"
                report.violation(
                    section,
                    Finding(
                        path,
                        lineno,
                        f"{match.group(0)!r} appears in {where}",
                        excerpt_at(text, starts, lineno),
                    ),
                )

    for allowance in NAME_ALLOWANCES:
        key = (allowance.path, allowance.token.lower())
        if key in applied_allowances:
            report.note(
                "Applied name exclusions (match found, permitted for a stated reason)",
                Finding(allowance.path, 0, f"{allowance.token!r}", allowance.reason),
            )
        else:
            report.note(
                "Stale allowlist entries (asset is gone - entry can be removed)",
                Finding(
                    allowance.path,
                    0,
                    f"{allowance.token!r} no longer appears here",
                ),
            )

    return masked_totals


# --------------------------------------------------------------------------
# Check D - size census
# --------------------------------------------------------------------------

ART_GEOMETRY = ("src/lib/game/art.ts", "src/lib/game/creatures.ts")


def is_test(path: str) -> bool:
    base = os.path.basename(path)
    return ".test." in base or ".spec." in base or path.startswith("e2e/")


def size_census(files: list[str]) -> list[tuple[str, int, int]]:
    """(label, file count, bytes) rows. Sorted-input driven, so deterministic."""

    def total(paths: list[str]) -> tuple[int, int]:
        return len(paths), sum(size_of(p) for p in paths)

    web_src = [f for f in files if f.startswith("src/") and not is_test(f)]
    web_public = [f for f in files if f.startswith("public/")]
    mobile_src = [
        f
        for f in files
        if (f.startswith("mobile/src/") or f.startswith("mobile/assets/"))
        and not is_test(f)
    ]
    tests = [f for f in files if is_test(f)]
    doc_media = [f for f in files if f.startswith(DOC_MEDIA_DIRS)]
    art = [f for f in files if f in ART_GEOMETRY]

    rows = [
        ("Shared engine + web source (src/, excluding tests)", *total(web_src)),
        ("  of which creature art geometry (both clients)", *total(art)),
        ("Web shipped static dir (public/)", *total(web_public)),
        ("iOS client source (mobile/src, mobile/assets)", *total(mobile_src)),
        ("Tests (src/**/*.test.*, e2e/) - not shipped", *total(tests)),
        ("Documentation media - not shipped", *total(doc_media)),
        ("Everything tracked or untracked-not-ignored", *total(files)),
    ]
    return [(label, count, size) for label, count, size in rows]


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def kib(n: int) -> str:
    return f"{n / 1024:.1f} KiB"


def render(report: Report, files: list[str], masked: dict[str, int], quiet: bool) -> str:
    out: list[str] = []
    add = out.append

    add("=" * 74)
    add("ASSET AND TRADEMARK AUDIT - Mathmon Battle League")
    add("=" * 74)
    add("")
    add(f"Files examined: {len(files)} (git-tracked plus untracked-not-ignored)")
    add("")

    if report.violations:
        add("-" * 74)
        add(f"VIOLATIONS ({report.violation_count})")
        add("-" * 74)
        for section in sorted(report.violations):
            findings = report.violations[section]
            add("")
            add(f"{section}  [{len(findings)}]")
            for finding in sorted(findings, key=lambda f: (f.path, f.line)):
                add(finding.render())
        add("")

    if not quiet:
        add("-" * 74)
        add("EXCLUSIONS APPLIED (and why)")
        add("-" * 74)
        add("")
        add("  Documentation is not scanned for trademarked names:")
        add("    README.md, CLAUDE.md, mobile/README.md, docs/**, mobile/docs/**")
        add("    These files legitimately describe what the project deliberately")
        add("    does NOT contain - README.md has a section titled 'A note on")
        add("    Pokemon' saying exactly that. Scanning them would make the audit")
        add("    fail for telling the truth.")
        add("")
        add("  The repository's own name is masked before matching:")
        add(f"    pattern {REPO_SLUG_PATTERN.pattern!r} (case-insensitive)")
        add("    The repo is called pokemon-game and the git remote URL embeds it,")
        add("    so the string appears unavoidably in Vercel import links and")
        add("    config. Masking is same-length, so line numbers stay correct.")
        if masked:
            for path in sorted(masked):
                add(f"      {masked[path]:3d} occurrence(s) masked in {path}")
        else:
            add("      (no occurrences outside documentation)")
        add("")
        add("  Lockfiles: `\"integrity\":` lines are skipped in " + ", ".join(LOCKFILES))
        add("    Those values are base64 digests and will contain arbitrary letter")
        add("    sequences by chance. Package names and resolved URLs are still")
        add("    scanned, so a dependency named after the franchise is still caught.")
        add("")
        add(f"  {SELF_PATH} is not scanned by checks B and C.")
        add("    It necessarily contains the very host list and name list it")
        add("    searches for. This is the audit's one blind spot; it is a single")
        add("    file, and it is reviewed like any other.")
        add("")
        add("  Markdown and docs/ are not scanned for remote asset hosts.")
        add("    The Vercel deploy badge in README.md is a remote image that")
        add("    renders on GitHub. It is documentation, not shipped app code.")
        add("")

        for section in sorted(report.notes):
            findings = report.notes[section]
            add("-" * 74)
            add(f"{section}  [{len(findings)}]")
            add("-" * 74)
            for finding in sorted(findings, key=lambda f: (f.path, f.line)):
                add(finding.render())
            add("")

    add("-" * 74)
    add("SIZE CENSUS - what actually ships")
    add("-" * 74)
    add("")
    add(f"  {'':52s}{'files':>7s}{'size':>13s}")
    for label, count, size in size_census(files):
        add(f"  {label:52s}{count:>7d}{kib(size):>13s}")
    add("")
    art_files = [f for f in files if f in ART_GEOMETRY]
    art_bytes = sum(size_of(f) for f in art_files)
    add(
        f"  All 36 creatures cost {kib(art_bytes)} of TypeScript geometry "
        f"({', '.join(ART_GEOMETRY)}),"
    )
    add("  shared verbatim by the web and iOS clients, and zero bytes of image")
    add("  assets. For comparison, the documentation screenshots - which no")
    add("  player ever downloads - are larger than the entire application.")
    add("")

    add("=" * 74)
    if report.failed:
        add(f"RESULT: FAIL - {report.violation_count} violation(s)")
        add("")
        add("The claim in README.md and CLAUDE.md that this repository ships no")
        add("third-party image, font or audio assets is currently FALSE.")
    else:
        add("RESULT: PASS")
        add("")
        add("No binary media outside the documentation directories, no remote")
        add("asset host referenced from code, and no trademarked creature name in")
        add("shipped source.")
    add("=" * 74)
    add("")
    add("Scope note: this audit proves the repository contains no third-party")
    add("*asset files* and fetches nothing at runtime. It cannot prove that")
    add("hand-written geometry is not a copy of someone else's drawing, and it")
    add("does not inspect node_modules. Those remain human judgements.")
    add("=" * 74)
    return "\n".join(out)


def main(argv: list[str]) -> int:
    quiet = "--quiet" in argv[1:]
    unknown = [a for a in argv[1:] if a not in ("--quiet",)]
    if unknown:
        sys.stderr.write(f"audit_assets: unknown argument(s): {' '.join(unknown)}\n")
        sys.stderr.write(__doc__ or "")
        return 2

    files = collect_files()
    report = Report()

    check_media(files, report)
    check_shipped_dirs(files, report)
    check_remote_refs(files, report)
    masked = check_trademarks(files, report)

    sys.stdout.write(render(report, files, masked, quiet) + "\n")
    return 1 if report.failed else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
