#!/usr/bin/env python3
"""Audit the committed screenshots in docs/screenshots/, without a browser.

Why this exists
---------------
`docs/screenshots/` is the visual record of the game. README.md embeds fourteen
of those images, and they are the only description of the app that a reader who
never runs it will ever see. They are generated by `e2e/screenshots.spec.ts`
(`npm run screenshots`), which needs a production build and a browser - far too
expensive to run on every push.

That leaves a gap, and it is a nastier one than it looks. `page.screenshot()`
succeeds whether the page rendered the game or a white rectangle. **A screenshot
suite that photographs a crash page passes exactly as happily as one that
photographs the game.** This project has already been bitten by that class of
bug on iOS, where a green simulator run turned out to be photographing a redbox,
and again here: `12-chinese.png` - the one image in the README showing the
Chinese interface - was byte-identical to `02-dashboard.png`, an entirely
English screen. The spec clicked the language toggle and then navigated, and
`page.addInitScript` re-seeded the English profile on that navigation. Nothing
failed. The suite went green and the README showed the wrong language for as
long as anyone cared to not look.

So this audit checks the *artifacts*, from the bytes up, with the standard
library alone: no browser, no build, no network, roughly ten seconds. It cannot
tell you the button is in the right place. It can tell you the file exists, is a
real PNG, is the size the viewport says it should be, is not blank, is not a
white crash page, and is not a copy of a different screen.

Properties
----------
P1  manifest    The set of PNGs on disk is exactly the set `screenshots.spec.ts`
                captures: no missing file, no orphan left behind by a renamed
                shot, no stray non-PNG in the directory, and every name follows
                the `NN-kebab-case` convention the README orders them by.
P2  decodable   Every file is a valid PNG all the way through: signature, chunk
                lengths and CRCs, an IHDR this audit can actually inspect, an
                IDAT stream that inflates to exactly the declared number of
                scanlines, and an IEND. A truncated or half-written capture dies
                here rather than being displayed as a broken image on GitHub.
P3  geometry    Pixel dimensions equal the viewport the spec configures for that
                shot times its device scale factor - 1280x800 for the desktop
                project from playwright.config.ts, 800x1720 for the phone-sized
                context the spec opens itself. A capture that silently fell back
                to a different viewport is a different picture of the app.
P4  legible     No image is blank. Exactly uniform is a violation; so is a near
                enough miss - too few distinct scanlines, too few distinct
                colours, one colour covering almost everything. And because
                every screen of this app is dark, a bright image is not a screen
                of this app: a mostly-white capture is an error overlay, a
                stylesheet that never loaded, or a page that never painted.
P5  distinct    No two screenshots contain the same pixels. Two names for one
                picture means one of the screens was never really captured, and
                the file dates and sizes look perfectly healthy while it is true.
                This is the property `12-chinese.png` violated.
P6  documented  Every `docs/screenshots/*.png` path referenced from the
                documentation exists. Screenshots no document references are
                reported as a note, not a violation - not every capture has to
                be embedded, but a broken image link in the README is a bug.

Reading the spec rather than a hard-coded list
----------------------------------------------
The expected manifest is parsed out of `e2e/screenshots.spec.ts` and
`playwright.config.ts`, never written down here. A hard-coded list would be a
second source of truth that drifts, and drift is the whole thing this audit is
built to notice: add a `shot(page, '17-whatever')` and forget to run
`npm run screenshots`, and P1 says so on the next push.

Determinism
-----------
No clock, no randomness, no network, no set iteration reaching the output: every
list is sorted before it is printed and every ratio is rounded. The colour
statistics sample a fixed lattice (every second row, every third pixel), which
is a fixed function of the image. Two runs on the same tree print byte-identical
output.

Usage:
    python3 scripts/audit_screenshots.py

Exit status
-----------
0  every property holds.
1  at least one property is violated. Each violation is named by its property.
2  the harness could not run - a missing spec, an unparseable config, an
   unreadable directory. Never a silent pass: this audit fails loudly rather
   than reporting all-clear on files it did not manage to inspect.
"""

from __future__ import annotations

import hashlib
import os
import re
import struct
import sys
import zlib
from collections import Counter
from dataclasses import dataclass

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SPEC_PATH = "e2e/screenshots.spec.ts"
CONFIG_PATH = "playwright.config.ts"
SHOT_DIR = "docs/screenshots"

# Documents that may embed a screenshot. Anything else in the tree is not
# expected to link one, and a link from a source file would be a bug of a
# different kind entirely.
DOC_FILES = ("README.md", "CLAUDE.md", "docs/README.md", "mobile/README.md")

NAME_PATTERN = re.compile(r"^\d{2}-[a-z0-9]+(?:-[a-z0-9]+)*$")


# ---------------------------------------------------------------------------
# P4 thresholds
# ---------------------------------------------------------------------------
#
# Every number below is a floor or a ceiling with at least an order of magnitude
# of headroom over the *worst* real screenshot in the set, measured rather than
# guessed. The point is to catch a capture that is not a screen of this game at
# all - blank, flat, or white - and to be nowhere near firing on a legitimately
# sparse screen. The sparsest real screen is 13-sign-in (935 sampled colours,
# 54% one colour, mean luminance 24); the brightest is 15-mobile-dashboard
# (mean luminance 42, 1.4% of pixels near-white).

MIN_FILE_BYTES = 4096
MIN_DISTINCT_ROWS = 16
MIN_DISTINCT_COLOURS = 64
MAX_DOMINANT_SHARE = 0.90
MAX_LIGHT_SHARE = 0.35
MAX_MEAN_LUMINANCE = 128.0

# "Near-white" for the light-share test. The app's own palette tops out at
# amber-300 and white text on a slate-950 panel; a screen where a third of the
# pixels are this bright is not this app.
LIGHT_CHANNEL_FLOOR = 200

# Colour statistics are computed on a fixed lattice rather than every pixel.
# Full-resolution counting in pure Python triples the runtime and moves no
# number that matters: the check is "is this a screen or a blank", not a
# histogram anyone reads.
ROW_SAMPLE_STEP = 2
COL_SAMPLE_STEP = 3


def die(message: str) -> "NoReturn":  # type: ignore[valid-type]
    sys.stderr.write(f"audit_screenshots: {message}\n")
    raise SystemExit(2)


# ---------------------------------------------------------------------------
# The manifest the spec claims to produce
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Shot:
    """One screenshot the spec captures, and the viewport it captures it at."""

    name: str
    test: str
    line: int
    width: int
    height: int
    scale: int

    @property
    def expected_px(self) -> tuple[int, int]:
        return self.width * self.scale, self.height * self.scale


def read_repo_text(relative: str) -> str:
    path = os.path.join(REPO_ROOT, relative)
    try:
        with open(path, encoding="utf-8") as handle:
            return handle.read()
    except OSError as exc:
        die(f"cannot read {relative}: {exc}")


def parse_desktop_viewport(source: str) -> tuple[int, int, int]:
    """The desktop project's viewport and device scale factor from the config.

    Playwright's `devices['Desktop Chrome']` is 1x, so an absent
    deviceScaleFactor means 1. The viewport is overridden explicitly in the
    config, which is what makes it parseable at all - if that ever stops being
    true this raises rather than guessing, because a guessed expected size would
    make P3 assert nothing.
    """
    match = re.search(
        r"name:\s*'desktop'.*?viewport:\s*\{\s*width:\s*(\d+),\s*height:\s*(\d+)\s*\}",
        source,
        re.DOTALL,
    )
    if not match:
        die(
            f"could not find the desktop project's viewport in {CONFIG_PATH}. "
            "P3 cannot check a size it cannot read; fix the parse rather than "
            "letting the audit pass without it."
        )
    scale_match = re.search(
        r"name:\s*'desktop'.*?deviceScaleFactor:\s*(\d+)", source, re.DOTALL
    )
    scale = int(scale_match.group(1)) if scale_match else 1
    return int(match.group(1)), int(match.group(2)), scale


def parse_spec(source: str, desktop: tuple[int, int, int]) -> list[Shot]:
    """Every `shot(page, 'name')` in the spec, with the viewport in force.

    The association is positional, which is enough because the spec is one flat
    file of `test(...)` blocks: a shot belongs to the most recent `test(` above
    it, and takes an explicit `browser.newContext({ viewport: ... })` from that
    same block if one appeared before it. The desktop project's viewport
    otherwise.
    """
    shots: list[Shot] = []
    test_name = "(top level)"
    width, height, scale = desktop

    test_re = re.compile(r"^\s*test\(\s*(['\"])(.*?)\1")
    viewport_re = re.compile(r"viewport:\s*\{\s*width:\s*(\d+),\s*height:\s*(\d+)\s*\}")
    scale_re = re.compile(r"deviceScaleFactor:\s*(\d+)")
    shot_re = re.compile(r"\bshot\(\s*\w+\s*,\s*(['\"])(.*?)\1\s*\)")
    out_re = re.compile(r"const OUT\s*=\s*['\"](.*?)['\"]")

    out_match = out_re.search(source)
    if not out_match:
        die(f"could not find the output directory (`const OUT = ...`) in {SPEC_PATH}")
    if out_match.group(1).rstrip("/") != SHOT_DIR:
        die(
            f"{SPEC_PATH} writes to {out_match.group(1)!r}, but this audit inspects "
            f"{SHOT_DIR!r}. One of the two moved."
        )

    for number, line in enumerate(source.split("\n"), start=1):
        test_match = test_re.match(line)
        if test_match:
            test_name = test_match.group(2)
            width, height, scale = desktop  # each block starts from the project default
        viewport_match = viewport_re.search(line)
        if viewport_match:
            width, height = int(viewport_match.group(1)), int(viewport_match.group(2))
            scale = 1
        scale_match = scale_re.search(line)
        if scale_match:
            scale = int(scale_match.group(1))
        for shot_match in shot_re.finditer(line):
            shots.append(
                Shot(shot_match.group(2), test_name, number, width, height, scale)
            )

    if not shots:
        die(
            f"parsed no `shot(page, '...')` calls out of {SPEC_PATH}. Either the spec "
            "stopped capturing anything or this parse is broken; both are worth a "
            "human look, and neither is a pass."
        )
    return shots


# ---------------------------------------------------------------------------
# PNG decoding (P2, and the pixels P3/P4/P5 need)
# ---------------------------------------------------------------------------

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"

# Bytes per pixel by colour type, at bit depth 8. Type 3 (palette) is one index
# byte per pixel and is expanded after unfiltering.
CHANNELS = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}


class BadPng(Exception):
    """This file is not a PNG this audit can vouch for. Always a P2 violation."""


@dataclass
class Image:
    width: int
    height: int
    colour_type: int
    rows: list[bytes]  # unfiltered, expanded to RGB or RGBA/grey as stored
    bpp: int


def parse_png(raw: bytes) -> Image:
    """Decode far enough to have real pixels, verifying every chunk on the way.

    Deliberately strict. A PNG that is merely *probably* fine is exactly the
    kind of thing this audit exists to refuse: a half-written capture from a
    killed test run truncates mid-IDAT and still renders its top half in a
    viewer, which is how a broken screenshot survives a human glance.
    """
    if len(raw) < len(PNG_SIGNATURE) or not raw.startswith(PNG_SIGNATURE):
        raise BadPng("does not start with the PNG signature")

    pos = len(PNG_SIGNATURE)
    header: tuple[int, ...] | None = None
    idat: list[bytes] = []
    palette = b""
    saw_end = False

    while pos < len(raw):
        if pos + 8 > len(raw):
            raise BadPng(f"file ends mid-chunk-header at byte {pos} of {len(raw)}")
        (length,) = struct.unpack(">I", raw[pos : pos + 4])
        kind = raw[pos + 4 : pos + 8]
        start = pos + 8
        end = start + length
        if end + 4 > len(raw):
            raise BadPng(
                f"chunk {kind.decode('latin-1')} at byte {pos} declares {length} bytes "
                f"but only {max(0, len(raw) - start)} remain - the file is truncated"
            )
        data = raw[start:end]
        (declared_crc,) = struct.unpack(">I", raw[end : end + 4])
        actual_crc = zlib.crc32(kind + data) & 0xFFFFFFFF
        if declared_crc != actual_crc:
            raise BadPng(
                f"chunk {kind.decode('latin-1')} at byte {pos} fails its CRC "
                f"({declared_crc:08x} declared, {actual_crc:08x} computed)"
            )
        pos = end + 4

        if kind == b"IHDR":
            if length != 13:
                raise BadPng(f"IHDR is {length} bytes, expected 13")
            header = struct.unpack(">IIBBBBB", data)
        elif kind == b"PLTE":
            palette = data
        elif kind == b"IDAT":
            idat.append(data)
        elif kind == b"IEND":
            saw_end = True

    if header is None:
        raise BadPng("has no IHDR chunk")
    if not saw_end:
        raise BadPng("has no IEND chunk - the file was never finished")
    if not idat:
        raise BadPng("has no IDAT chunk - there are no pixels in it at all")

    width, height, depth, colour_type, compression, filter_method, interlace = header
    if width == 0 or height == 0:
        raise BadPng(f"declares a {width}x{height} image")
    if compression != 0 or filter_method != 0:
        raise BadPng(f"uses compression {compression}/filter method {filter_method}")
    if depth != 8:
        raise BadPng(
            f"is {depth}-bit. This audit inspects 8-bit PNGs, which is what "
            "Playwright emits; it will not pass a file whose pixels it cannot read."
        )
    if interlace != 0:
        raise BadPng("is interlaced, and this audit cannot inspect its pixels")
    if colour_type not in CHANNELS:
        raise BadPng(f"has unknown colour type {colour_type}")

    bpp = CHANNELS[colour_type]
    stride = width * bpp

    try:
        data = zlib.decompress(b"".join(idat))
    except zlib.error as exc:
        raise BadPng(f"IDAT stream will not inflate: {exc}") from exc

    expected = height * (stride + 1)
    if len(data) != expected:
        raise BadPng(
            f"IDAT inflates to {len(data)} bytes, expected {expected} "
            f"({height} scanlines of {stride}+1) - the image is truncated or malformed"
        )

    rows = _unfilter(data, width, height, bpp, stride)

    if colour_type == 3:
        if not palette:
            raise BadPng("is palette-coloured but carries no PLTE chunk")
        rows = [_expand_palette(row, palette) for row in rows]
        bpp = 3

    return Image(width, height, colour_type, rows, bpp)


def _unfilter(data: bytes, width: int, height: int, bpp: int, stride: int) -> list[bytes]:
    """Reverse the five PNG scanline filters. Hot loop; written for speed."""
    rows: list[bytes] = []
    prev = bytearray(stride)
    pos = 0
    for _ in range(height):
        filter_type = data[pos]
        pos += 1
        line = bytearray(data[pos : pos + stride])
        pos += stride

        if filter_type == 0:
            pass
        elif filter_type == 1:
            for i in range(bpp, stride):
                line[i] = (line[i] + line[i - bpp]) & 255
        elif filter_type == 2:
            line = bytearray([(a + b) & 255 for a, b in zip(line, prev)])
        elif filter_type == 3:
            for i in range(min(bpp, stride)):
                line[i] = (line[i] + (prev[i] >> 1)) & 255
            for i in range(bpp, stride):
                line[i] = (line[i] + ((line[i - bpp] + prev[i]) >> 1)) & 255
        elif filter_type == 4:
            for i in range(min(bpp, stride)):
                line[i] = (line[i] + prev[i]) & 255
            for i in range(bpp, stride):
                a = line[i - bpp]
                b = prev[i]
                c = prev[i - bpp]
                p = a + b - c
                pa = p - a
                pb = p - b
                pc = p - c
                if pa < 0:
                    pa = -pa
                if pb < 0:
                    pb = -pb
                if pc < 0:
                    pc = -pc
                if pa <= pb and pa <= pc:
                    predictor = a
                elif pb <= pc:
                    predictor = b
                else:
                    predictor = c
                line[i] = (line[i] + predictor) & 255
        else:
            raise BadPng(f"scanline uses unknown filter type {filter_type}")

        rows.append(bytes(line))
        prev = line
    return rows


def _expand_palette(row: bytes, palette: bytes) -> bytes:
    out = bytearray(len(row) * 3)
    limit = len(palette) // 3
    for i, index in enumerate(row):
        if index >= limit:
            raise BadPng(f"palette index {index} is outside a {limit}-entry PLTE")
        out[i * 3 : i * 3 + 3] = palette[index * 3 : index * 3 + 3]
    return bytes(out)


# ---------------------------------------------------------------------------
# Image statistics (P4, P5)
# ---------------------------------------------------------------------------


@dataclass
class Stats:
    distinct_rows: int
    distinct_colours: int
    dominant_share: float
    light_share: float
    mean_luminance: float
    uniform: bool
    digest: str


def measure(image: Image) -> Stats:
    rows = image.rows
    bpp = image.bpp
    flat = b"".join(rows)
    uniform = flat == flat[:bpp] * (image.width * image.height)

    sampled: Counter[bytes] = Counter()
    step = bpp * COL_SAMPLE_STEP
    for y in range(0, image.height, ROW_SAMPLE_STEP):
        row = rows[y]
        sampled.update(row[x : x + bpp] for x in range(0, image.width * bpp, step))

    total = sum(sampled.values())
    dominant = max(sampled.values()) / total
    luminance_sum = 0.0
    light = 0
    for pixel, count in sampled.items():
        if bpp >= 3:
            red, green, blue = pixel[0], pixel[1], pixel[2]
        else:
            red = green = blue = pixel[0]
        luminance_sum += (0.299 * red + 0.587 * green + 0.114 * blue) * count
        if (
            red >= LIGHT_CHANNEL_FLOOR
            and green >= LIGHT_CHANNEL_FLOOR
            and blue >= LIGHT_CHANNEL_FLOOR
        ):
            light += count

    digest = hashlib.sha256()
    digest.update(f"{image.width}x{image.height}:".encode())
    digest.update(flat)

    return Stats(
        distinct_rows=len(set(rows)),
        distinct_colours=len(sampled),
        dominant_share=dominant,
        light_share=light / total,
        mean_luminance=luminance_sum / total,
        uniform=uniform,
        digest=digest.hexdigest(),
    )


# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------

Violation = tuple[str, str]


def check_manifest(shots: list[Shot], on_disk: list[str], extras: list[str]) -> list[Violation]:
    """P1: the directory holds exactly the shots the spec captures."""
    violations: list[Violation] = []

    seen: dict[str, Shot] = {}
    for shot in shots:
        if shot.name in seen:
            first = seen[shot.name]
            violations.append(
                (
                    "P1 manifest",
                    f"{SPEC_PATH} captures {shot.name!r} twice (line {first.line} in "
                    f"{first.test!r}, line {shot.line} in {shot.test!r}) - the second "
                    f"overwrites the first, so one of those screens is never recorded",
                )
            )
        seen[shot.name] = shot
        if not NAME_PATTERN.match(shot.name):
            violations.append(
                (
                    "P1 manifest",
                    f"{SPEC_PATH}:{shot.line} captures {shot.name!r}, which is not "
                    f"NN-kebab-case - the README orders these by their number",
                )
            )

    expected = set(seen)
    present = set(on_disk)

    for name in sorted(expected - present):
        violations.append(
            (
                "P1 manifest",
                f"{SHOT_DIR}/{name}.png is missing - {SPEC_PATH}:{seen[name].line} "
                f"captures it. Run `npm run screenshots`.",
            )
        )
    for name in sorted(present - expected):
        violations.append(
            (
                "P1 manifest",
                f"{SHOT_DIR}/{name}.png is an orphan - no shot in {SPEC_PATH} produces "
                f"it, so nothing regenerates it and it will rot",
            )
        )
    for extra in sorted(extras):
        violations.append(
            (
                "P1 manifest",
                f"{SHOT_DIR}/{extra} is not a .png - this directory holds generated "
                f"captures and nothing else",
            )
        )
    return violations


def check_file(name: str, path: str, shot: Shot | None) -> tuple[list[Violation], Stats | None]:
    """P2, P3 and P4 for one file. Returns its stats when they could be measured."""
    violations: list[Violation] = []
    label = f"{SHOT_DIR}/{name}.png"

    try:
        with open(path, "rb") as handle:
            raw = handle.read()
    except OSError as exc:
        return [("P2 decodable", f"{label} cannot be read: {exc}")], None

    if len(raw) < MIN_FILE_BYTES:
        violations.append(
            (
                "P2 decodable",
                f"{label} is {len(raw)} bytes. No real capture of this app is under "
                f"{MIN_FILE_BYTES}; this one is empty, stubbed or half-written",
            )
        )

    try:
        image = parse_png(raw)
    except BadPng as exc:
        violations.append(("P2 decodable", f"{label} {exc}"))
        return violations, None

    if shot is not None:
        expected = shot.expected_px
        if (image.width, image.height) != expected:
            violations.append(
                (
                    "P3 geometry",
                    f"{label} is {image.width}x{image.height}, expected "
                    f"{expected[0]}x{expected[1]} "
                    f"({shot.width}x{shot.height} viewport at {shot.scale}x, from "
                    f"{SPEC_PATH}:{shot.line})",
                )
            )

    stats = measure(image)

    if stats.uniform:
        violations.append(
            (
                "P4 legible",
                f"{label} is a single flat colour over all "
                f"{image.width * image.height} pixels - it is blank",
            )
        )
    else:
        if stats.distinct_rows < MIN_DISTINCT_ROWS:
            violations.append(
                (
                    "P4 legible",
                    f"{label} has only {stats.distinct_rows} distinct scanline(s), "
                    f"minimum {MIN_DISTINCT_ROWS} - there is nothing drawn on it",
                )
            )
        if stats.distinct_colours < MIN_DISTINCT_COLOURS:
            violations.append(
                (
                    "P4 legible",
                    f"{label} samples only {stats.distinct_colours} distinct colour(s), "
                    f"minimum {MIN_DISTINCT_COLOURS}",
                )
            )
        if stats.dominant_share > MAX_DOMINANT_SHARE:
            violations.append(
                (
                    "P4 legible",
                    f"{label} is {stats.dominant_share:.1%} one single colour, "
                    f"limit {MAX_DOMINANT_SHARE:.0%} - very close to blank",
                )
            )

    if stats.light_share > MAX_LIGHT_SHARE:
        violations.append(
            (
                "P4 legible",
                f"{label} is {stats.light_share:.1%} near-white pixels, limit "
                f"{MAX_LIGHT_SHARE:.0%}. Every screen of this app is dark, so this is "
                f"an error overlay, an unstyled page, or a capture that never painted",
            )
        )
    if stats.mean_luminance > MAX_MEAN_LUMINANCE:
        violations.append(
            (
                "P4 legible",
                f"{label} has mean luminance {stats.mean_luminance:.1f}, limit "
                f"{MAX_MEAN_LUMINANCE:.0f} - far too bright to be a screen of this app",
            )
        )

    return violations, stats


def check_distinct(stats: dict[str, Stats]) -> list[Violation]:
    """P5: no two screenshots are the same picture."""
    groups: dict[str, list[str]] = {}
    for name, stat in stats.items():
        groups.setdefault(stat.digest, []).append(name)

    violations: list[Violation] = []
    for digest, names in sorted(groups.items()):
        if len(names) > 1:
            listed = ", ".join(f"{n}.png" for n in sorted(names))
            violations.append(
                (
                    "P5 distinct",
                    f"{listed} contain identical pixels ({digest[:12]}) - they claim to "
                    f"be different screens, so at least one of them was never captured",
                )
            )
    return violations


def check_documented(on_disk: list[str]) -> tuple[list[Violation], dict[str, list[str]]]:
    """P6: documented image paths resolve. Returns the reference map for the note."""
    reference_re = re.compile(re.escape(SHOT_DIR) + r"/([A-Za-z0-9_.-]+?)\.png")
    references: dict[str, list[str]] = {}
    violations: list[Violation] = []
    present = set(on_disk)

    for doc in DOC_FILES:
        path = os.path.join(REPO_ROOT, doc)
        if not os.path.exists(path):
            continue
        try:
            with open(path, encoding="utf-8") as handle:
                text = handle.read()
        except OSError as exc:
            die(f"cannot read {doc}: {exc}")
        for match in reference_re.finditer(text):
            name = match.group(1)
            references.setdefault(name, []).append(doc)
            if name not in present:
                line = text.count("\n", 0, match.start()) + 1
                violations.append(
                    (
                        "P6 documented",
                        f"{doc}:{line} embeds {SHOT_DIR}/{name}.png, which does not "
                        f"exist - that is a broken image on GitHub",
                    )
                )

    for name in references:
        references[name] = sorted(set(references[name]))
    return violations, references


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


def list_directory() -> tuple[list[str], list[str]]:
    """(screenshot names, non-PNG entries) in the screenshot directory."""
    path = os.path.join(REPO_ROOT, SHOT_DIR)
    if not os.path.isdir(path):
        die(f"{SHOT_DIR}/ does not exist")
    try:
        entries = sorted(os.listdir(path))
    except OSError as exc:
        die(f"cannot list {SHOT_DIR}/: {exc}")

    names = [e[:-4] for e in entries if e.endswith(".png")]
    extras = [e for e in entries if not e.endswith(".png")]
    return names, extras


def main(argv: list[str]) -> int:
    unknown = argv[1:]
    if unknown:
        sys.stderr.write(
            f"audit_screenshots: unknown argument(s): {' '.join(unknown)}\n"
        )
        sys.stderr.write(__doc__ or "")
        return 2

    desktop = parse_desktop_viewport(read_repo_text(CONFIG_PATH))
    shots = parse_spec(read_repo_text(SPEC_PATH), desktop)
    by_name = {shot.name: shot for shot in shots}

    on_disk, extras = list_directory()

    violations: list[Violation] = []
    violations += check_manifest(shots, on_disk, extras)

    stats: dict[str, Stats] = {}
    sizes: dict[str, int] = {}
    for name in on_disk:
        path = os.path.join(REPO_ROOT, SHOT_DIR, f"{name}.png")
        sizes[name] = os.path.getsize(path)
        file_violations, stat = check_file(name, path, by_name.get(name))
        violations += file_violations
        if stat is not None:
            stats[name] = stat

    violations += check_distinct(stats)
    documented_violations, references = check_documented(on_disk)
    violations += documented_violations

    print("Mathmon screenshot audit")
    print("========================")
    print(f"spec: {SPEC_PATH}   captures: {len(shots)}   on disk: {len(on_disk)}")
    print(
        f"desktop viewport from {CONFIG_PATH}: "
        f"{desktop[0]}x{desktop[1]} at {desktop[2]}x"
    )
    print()

    width = max([len(n) for n in on_disk] + [10])
    print(
        f"  {'screenshot'.ljust(width)}  {'pixels':>11}  {'KiB':>7}  {'colours':>7}  "
        f"{'top':>6}  {'white':>6}  {'lum':>6}  docs"
    )
    print(f"  {'-' * (width + 56)}")
    for name in on_disk:
        stat = stats.get(name)
        shot = by_name.get(name)
        where = ",".join(references.get(name, [])) or "-"
        if stat is None:
            print(f"  {name.ljust(width)}  {'unreadable':>11}")
            continue
        shot_size = (
            f"{shot.expected_px[0]}x{shot.expected_px[1]}" if shot else "no shot"
        )
        print(
            f"  {name.ljust(width)}  {shot_size:>11}  {sizes[name] / 1024:>7.0f}  "
            f"{stat.distinct_colours:>7}  {stat.dominant_share:>6.1%}  "
            f"{stat.light_share:>6.1%}  {stat.mean_luminance:>6.1f}  {where}"
        )
    print()
    print(
        "  top = share of the single most common colour, white = share of near-white"
    )
    print(
        "  pixels, lum = mean luminance. This app is dark on every screen, so a bright"
    )
    print("  row here is a crash page, not a screen.")

    unreferenced = sorted(set(on_disk) - set(references))
    if unreferenced:
        print()
        print("  Captured but embedded in no document (not a violation - a capture may")
        print("  exist purely as a record):")
        for name in unreferenced:
            print(f"    {SHOT_DIR}/{name}.png")

    print()
    if violations:
        print("FAIL")
        for prop, message in sorted(violations):
            print(f"  {prop}: {message}")
        properties = sorted({prop for prop, _ in violations})
        print()
        print(
            f"  {len(violations)} violation(s) across {len(properties)} propert(ies): "
            f"{', '.join(properties)}"
        )
        return 1

    print(
        "OK: P1 manifest, P2 decodable, P3 geometry, P4 legible, P5 distinct, "
        "P6 documented."
    )
    print()
    print("Scope note: this proves each screenshot is a real, distinct, correctly")
    print("sized, non-blank picture of a dark-themed screen. It cannot prove the")
    print("picture is of the screen its filename claims, or that it is current -")
    print("only re-running `npm run screenshots` does that.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
